// 36 states
export const nigeriaStates = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const ROLES = [
  {
    label: "I want to hire an artisan",
    value: "CLIENT",
  },
  {
    label: "I am an artisan",
    value: "WORKER",
  },
];

import {
  FaHammer,
  FaPaintRoller,
  FaPlug,
  FaTools,
  FaToilet,
  FaFan,
  FaCogs,
  FaCarCrash,
  FaBroom,
  FaTree,
  FaLock,
  FaFireExtinguisher,
  FaTshirt,
  FaTruckPickup,
  FaWindowRestore,
  FaRulerCombined,
  FaShower,
  FaTruck,
  FaCouch,
  FaSolarPanel,
} from "react-icons/fa";

import { FaBolt, FaWrench } from "react-icons/fa";

import userPhoto from "../assets/user-photo.png";

export const artisanCategories = [
  {
    id: 1,
    title: "Carpenters",
    icon: FaHammer,
    providers: 124,
  },
  {
    id: 2,
    title: "Painters",
    icon: FaPaintRoller,
    providers: 98,
  },
  {
    id: 3,
    title: "Electricians",
    icon: FaPlug,
    providers: 87,
  },
  {
    id: 4,
    title: "Plumbers",
    icon: FaToilet,
    providers: 76,
  },
  {
    id: 5,
    title: "AC Technicians",
    icon: FaFan,
    providers: 52,
  },
  {
    id: 6,
    title: "Auto Mechanics",
    icon: FaCarCrash,
    providers: 65,
  },
  {
    id: 7,
    title: "Welders",
    icon: FaTools,
    providers: 41,
  },
  {
    id: 8,
    title: "Technicians",
    icon: FaCogs,
    providers: 103,
  },
  {
    id: 9,
    title: "Cleaners",
    icon: FaBroom,
    providers: 89,
  },
  {
    id: 10,
    title: "Gardeners",
    icon: FaTree,
    providers: 72,
  },
  {
    id: 11,
    title: "Security Experts",
    icon: FaLock,
    providers: 38,
  },
  {
    id: 12,
    title: "Fire Safety",
    icon: FaFireExtinguisher,
    providers: 22,
  },
  {
    id: 13,
    title: "Tailors",
    icon: FaTshirt,
    providers: 49,
  },
  {
    id: 14,
    title: "Movers",
    icon: FaTruckPickup,
    providers: 34,
  },
  {
    id: 15,
    title: "Window Installers",
    icon: FaWindowRestore,
    providers: 29,
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Chinedu Okafor",
    role: "Homeowner, Lagos",
    message:
      "Laborly connected me with a reliable electrician in just minutes. The process was smooth and stress-free!",
    image: "/images/testimonials/chinedu.jpg",
    rating: 5,
  },
  {
    id: 2,
    name: "Aisha Bello",
    role: "Business Owner, Abuja",
    message:
      "I needed urgent plumbing work at my shop and Laborly delivered! Fast service and great professionals.",
    image: "/images/testimonials/aisha.jpg",
    rating: 4,
  },
  {
    id: 3,
    name: "Tunde Balogun",
    role: "Construction Manager, Ibadan",
    message:
      "Laborly makes it super easy to find trustworthy artisans. I highly recommend it to anyone managing projects.",
    image: "/images/testimonials/tunde.jpg",
    rating: 5,
  },
  {
    id: 4,
    name: "Grace Nwankwo",
    role: "Interior Designer, Port Harcourt",
    message:
      "The handyman I hired through Laborly exceeded my expectations. Punctual, professional, and skilled!",
    image: "/images/testimonials/grace.jpg",
    rating: 5,
  },
  {
    id: 5,
    name: "Joseph Adeyemi",
    role: "Landlord, Enugu",
    message:
      "It's hard to find reliable artisans, but Laborly really came through. Now I use it for all my rental properties.",
    image: "/images/testimonials/joseph.jpg",
    rating: 4,
  },
];

// Labourers Data
export const profileData = [
  {
    id: 1,
    name: "John Okoro",
    role: "Professional Carpenter",
    location: "Lagos",
    experience: "7 years experience",
    skills: [
      "Furniture Making",
      "Door Repairs",
      "Wood Finishing",
      "Custom Cabinetry",
      "Wood Carving",
      "Framing",
      "Trim Installation",
      "Deck Construction",
      "Restoration & Refinishing",
      "Blueprint Reading",
      "Joinery",
      "Sanding & Polishing",
      "Power Tool Operation",
      "Shelving Installation",
      "Wooden Flooring Installation",
    ],
    rating: 4.8,
    jobsCompleted: 120,
    image: userPhoto,
    icon: FaHammer,
    shortBio:
      "Detail-oriented carpenter known for clean finishes and custom woodwork. With over a decade of hands-on experience, I specialize in designing and constructing bespoke furniture, cabinetry, and interior wood accents. My work reflects precision, craftsmanship, and a passion for bringing clients’ visions to life. Whether it’s restoring vintage pieces or building from scratch, I approach every project with care, commitment, and a dedication to quality that stands the test of time.",
  },
  {
    id: 2,
    name: "Amina Yusuf",
    role: "Certified Painter",
    location: "Abuja",
    experience: "5 years experience",
    skills: [
      "Interior Painting",
      "Wall Designs",
      "Color Consultation",
      "Custom Mural Art",
      "Textured Wall Techniques",
      "Paint Restoration",
      "Faux Finishing",
      "Eco-friendly Paint Solutions",
    ],
    rating: 4,
    jobsCompleted: 95,
    image: userPhoto,
    icon: FaPaintRoller,
    shortBio:
      "Amina is a passionate and certified painter with an artistic eye for detail. With over five years of experience transforming residential and commercial interiors, she combines color theory with practical execution to deliver stunning results. From vibrant feature walls to calming pastel tones, Amina provides professional guidance on color consultation and finishes. Her clients praise her for reliability, cleanliness, and a creative touch that turns plain walls into vibrant expressions of personality. Whether you're looking for a subtle refresh or a complete makeover, Amina brings both flair and finesse to every project.",
  },
  {
    id: 3,
    name: "Chuka Emeka",
    role: "General Handyman",
    location: "Enugu",
    experience: "10+ years experience",
    skills: [
      "Repairs",
      "Installations",
      "Maintenance",
      "Furniture Assembly",
      "Ceiling and Roofing Fixes",
      "TV Mounting & Electrical Fittings",
      "Minor Plumbing",
      "General Carpentry",
    ],
    rating: 2,
    jobsCompleted: 200,
    image: userPhoto,
    icon: FaTools,
    shortBio:
      "Chuka is a seasoned handyman offering all-around repair, installation, and maintenance solutions with a hands-on approach to solving household and office challenges. For over a decade, he's been the go-to guy for those tricky tasks that require precision, strength, and versatility. His work spans a wide range — from fixing leaky faucets to assembling furniture and ensuring electrical fittings are safe and secure. Known for his punctuality, work ethic, and no-nonsense attitude, Chuka takes pride in getting the job done right the first time. He brings years of experience and genuine care to every task, ensuring every space functions smoothly.",
  },
  {
    id: 4,
    name: "Bola Adebayo",
    role: "Electrical Technician",
    location: "Ibadan",
    experience: "8 years experience",
    skills: [
      "Wiring",
      "Electrical Repairs",
      "Power Backup Installation",
      "Solar Inverter Wiring",
      "Panel Upgrades",
      "Socket & Switch Installations",
      "Electrical Safety Inspections",
      "Generator Maintenance",
    ],
    rating: 4.7,
    jobsCompleted: 110,
    image: userPhoto,
    icon: FaBolt,
    shortBio:
      "Bola is a licensed and dependable electrical technician delivering safe and high-performance solutions to homes, offices, and industrial buildings. With over eight years of hands-on experience, Bola expertly handles wiring projects, diagnostics, energy backup setups, and more. His technical expertise ensures that all electrical systems are efficient, up to code, and built to last. Bola’s meticulous planning and attention to safety make him a trusted name in the field, and he goes above and beyond to ensure power reliability and customer satisfaction with every job.",
  },
  {
    id: 5,
    name: "Kelvin Nwachukwu",
    role: "Plumber",
    location: "Port Harcourt",
    experience: "6 years experience",
    skills: [
      "Leak Repairs",
      "Pipe Installation",
      "Bathroom Fittings",
      "Water Heater Installation",
      "Drain Cleaning",
      "Toilet Unclogging",
      "Kitchen Sink Fixes",
      "Emergency Plumbing Services",
    ],
    rating: 4.5,
    jobsCompleted: 88,
    image: userPhoto,
    icon: FaWrench,
    shortBio:
      "Kelvin is a professional plumber delivering efficient, clean, and long-lasting solutions. He tackles both emergency and planned plumbing jobs, including pipe installations, bathroom fittings, and kitchen upgrades. Clients value his quick response time, clear communication, and the respect he shows for their space and time. From major leaks to water heater installations, Kelvin ensures everything flows smoothly again — literally. He believes every drop counts, and he applies that mindset to both customer service and technical excellence.",
  },
  {
    id: 6,
    name: "Grace Onyekachi",
    role: "AC & Cooling Technician",
    location: "Benin City",
    experience: "9 years experience",
    skills: [
      "AC Servicing",
      "Cooling System Installation",
      "Thermostat Repairs",
      "Duct Cleaning",
      "Refrigerant Recharge",
      "Smart Thermostat Setup",
      "Compressor Replacement",
      "Split Unit Mounting",
    ],
    rating: 4.8,
    jobsCompleted: 102,
    image: userPhoto,
    icon: FaFan,
    shortBio:
      "Grace is an expert AC and cooling technician dedicated to creating comfortable environments in homes and workplaces. With a sharp understanding of air flow, cooling efficiency, and system diagnostics, she installs, maintains, and repairs air conditioning units of all types. Her customers rave about her punctuality, expertise, and commitment to providing long-term cooling solutions. From annual servicing to emergency fixes, Grace ensures you never have to sweat through a hot day again. She’s your go-to for a cooler, more efficient space.",
  },
  {
    id: 7,
    name: "Tunde Ayodele",
    role: "Tiler & Interior Finisher",
    location: "Ilorin",
    experience: "6 years experience",
    skills: [
      "Wall Tiling",
      "Bathroom Finishing",
      "Grouting",
      "Tile Restoration",
      "Patterned Tile Layouts",
      "Kitchen Backsplash Installations",
      "Stone Cladding",
      "Floor Leveling & Polishing",
    ],
    rating: 4.4,
    jobsCompleted: 76,
    image: userPhoto,
    icon: FaRulerCombined,
    shortBio:
      "Tunde is a tiling specialist with a keen eye for detail and a passion for transforming ordinary surfaces into stunning masterpieces. With a strong background in interior finishes, he offers stylish and durable installations that enhance the beauty and functionality of every room. From bathrooms to living spaces, Tunde brings symmetry, precision, and a touch of artistic flair to every tile placement. Whether you’re going for sleek modern tiles or intricate patterns, he guarantees a flawless finish that lasts for years.",
  },
  {
    id: 8,
    name: "Zainab Bello",
    role: "Bathroom Installer",
    location: "Osogbo",
    experience: "4 years experience",
    skills: [
      "Shower Fittings",
      "Toilet Installations",
      "Plumbing Fixes",
      "Bathtub Setup",
      "Tiling & Waterproofing",
      "Sink Installations",
      "Mirror Mounting",
      "Luxury Bathroom Remodeling",
    ],
    rating: 4.5,
    jobsCompleted: 65,
    image: userPhoto,
    icon: FaShower,
    shortBio:
      "Zainab specializes in modern and functional bathroom installations that blend elegance with practicality. Whether you're planning a sleek renovation or starting from scratch, she brings your vision to life with precision and professionalism. Her experience spans both residential and commercial projects, delivering top-quality fittings, tiling, and plumbing adjustments. Zainab’s attention to detail ensures that every aspect — from drainage to décor — is handled with expert care. Clients appreciate her collaborative approach and design insights.",
  },
  {
    id: 9,
    name: "Ibrahim Sule",
    role: "Mover & Relocation Expert",
    location: "Jos",
    experience: "9 years experience",
    skills: [
      "Packing",
      "Heavy Lifting",
      "Logistics",
      "Furniture Disassembly & Reassembly",
      "Fragile Item Handling",
      "Office Relocation",
      "Vehicle Loading & Unloading",
      "Storage Solutions",
    ],
    rating: 4.6,
    jobsCompleted: 130,
    image: userPhoto,
    icon: FaTruck,
    shortBio:
      "Ibrahim is a professional mover who takes the stress out of relocation. With nearly a decade of experience in packing, lifting, organizing, and transporting belongings, he ensures a smooth transition whether you're moving across the street or across states. Ibrahim and his team handle every item with care — from heavy furniture to delicate antiques — and prioritize timeliness, organization, and customer satisfaction. His thorough planning and problem-solving skills make every move efficient and damage-free.",
  },
  {
    id: 10,
    name: "Ngozi Chukwu",
    role: "Solar Panel Installer",
    location: "Awka",
    experience: "5 years experience",
    skills: [
      "Solar Setup",
      "Battery Installation",
      "Energy Consulting",
      "Inverter Installation",
      "System Design & Load Calculation",
      "Panel Cleaning & Maintenance",
      "Off-Grid Setup",
      "Renewable Energy Audits",
    ],
    rating: 4.7,
    jobsCompleted: 83,
    image: userPhoto,
    icon: FaSolarPanel,
    shortBio:
      "Ngozi is a certified solar energy technician providing clean, cost-saving power solutions for homes and businesses. With a passion for sustainability and technical accuracy, she designs and installs efficient systems tailored to clients’ energy needs. Ngozi walks clients through the entire process — from consulting to installation — and ensures every component functions optimally. Her systems are built to last and help reduce reliance on the national grid. Whether you're going solar for cost savings or environmental impact, Ngozi makes clean energy easy and effective.",
  },
  {
    id: 11,
    name: "Femi Afolabi",
    role: "Furniture Upholsterer",
    location: "Abeokuta",
    experience: "8 years experience",
    skills: [
      "Couch Repair",
      "Foam Replacement",
      "Re-upholstery",
      "Fabric Selection",
      "Frame Strengthening",
      "Vintage Furniture Restoration",
      "Leather Stitching",
      "Custom Cushion Design",
    ],
    rating: 4.5,
    jobsCompleted: 97,
    image: userPhoto,
    icon: FaCouch,
    shortBio:
      "Femi is a master upholsterer with years of experience breathing new life into worn-out furniture. From classic couches to custom chairs, he transforms tired and torn pieces into statement furniture that looks and feels brand new. Femi’s deep knowledge of fabrics, foams, and stitching techniques allows him to tailor every restoration to the client’s taste and comfort needs. With a mix of tradition and innovation, Femi ensures that sentimental or high-end pieces regain their former glory and more.",
  },
  {
    id: 12,
    name: "Rita Obasi",
    role: "Locksmith",
    location: "Calabar",
    experience: "6 years experience",
    skills: [
      "Key Duplication",
      "Lock Repairs",
      "Emergency Unlocking",
      "Digital Lock Setup",
      "Car Lock Solutions",
      "Security System Advice",
      "Master Key Systems",
      "Lock Re-keying",
    ],
    rating: 4.6,
    jobsCompleted: 72,
    image: userPhoto,
    icon: FaLock,
    shortBio:
      "Rita is a skilled locksmith offering fast, reliable, and secure lock solutions for residential, commercial, and automotive needs. Whether you're locked out at midnight or upgrading your property’s security, Rita responds swiftly with expert tools and know-how. She’s trusted by homes and businesses across Calabar for her discretion, technical ability, and 24/7 emergency service. From advanced smart locks to traditional keys, Rita helps protect what matters most with confidence and care.",
  },
];

//
